[package]
name = "biodex"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
clap = { version = "4.5.53", features = ["derive"] }
dotenv = "0.15.0"
log = "0.4.29"
log4rs = "1.4.0"
solana-program = "3.0.0"
solana-sdk = "3.0.0"

